### ISSUE TITLE
Avoid  multiple definition of XXX

### ISSUE THREAD

**Issue by qyvlik** [simonbrunel/qtpromise#1]
Avoid multiple definition of XXX, use `static inline` may be better.

---

[qpromisehelpers.h#L21](https://github.com/simonbrunel/qtpromise/blob/cba11e63414e70d5bd892e3a320b0d75051fb3c3/src/qtpromise/qpromisehelpers.h#L21)

[qpromisehelpers.h#L30](https://github.com/simonbrunel/qtpromise/blob/master/src/qtpromise/qpromisehelpers.h#L30)

[qpromisehelpers.h#L30](https://github.com/simonbrunel/qtpromise/blob/master/src/qtpromise/qpromisehelpers.h#L35)

**Comment by simonbrunel** [comment]
@qyvlik thanks. `inline` is missing to avoid the multiple definitions, not sure that `static` is useful.

**Comment by simonbrunel** [comment]
Fixed in 5d6bcc40ec
