### ISSUE TITLE
Raising the minimum requirement for Qt to Qt 5.6 LTS

### ISSUE THREAD

**Issue by pwuertz** [simonbrunel/qtpromise#16]
@simonbrunel Hi! How attached are you to the minimum required Qt version? Any particular reason for choosing 5.4 instead of, say version 5.6 (LTS and oldest version still supported by Qt)? The reason I'm asking is because I'm having trouble making my unit tests pass on Travis due to Qt bugs present in 5.4, which are fixed in 5.6. Appveyor tests already use 5.6 as minimum version and are doing fine.

Other than that I also had to upgrade the GCC on Travis from 4.8 to 4.9, also due to a bug in the old version. The tests still comply to the minimum requirement of using C++11, so this is fine I guess?

**Comment by simonbrunel** [comment]
I'm fine upgrading the minimum requirements to 5.6.

Can you submit a PR with only that changes?
