### ISSUE TITLE
visual studio 2013

### ISSUE THREAD

**Issue by paperab** [simonbrunel/qtpromise#2]
In visual studio 2013 the test projects do not compile. 
What is the minimum version of compilers to use the software?

**Comment by simonbrunel** [comment]
@paperab I can't say for sure what versions of compilers are supported. It requires a subset of C++11 features and works at least with with MSVC 2015 and GCC 4.8.4. Can you post the compilation errors you get while compiling with MSVC 2013?

**Comment by simonbrunel** [comment]
Installed MSVC 2013 and [fixed complication issues](/simonbrunel/qtpromise/commit/389c76e608a6299d1e4334aa028ff20cb4f7fe6d): can you checkout the [msvc-2013](/simonbrunel/qtpromise/tree/msvc-2013) branch and confirm that it works for you?

**Comment by paperab** [comment]
It seems to work well. Very good. 
The branch msvc-2013 is compiling and the full set of tests in /qpromise are passing perfectly.

********* Start testing of tst_qpromise *********
Config: Using QtTest library 5.7.0, Qt 5.7.0 (i386-little_endian-ilp32 shared (dynamic) release build; by MSVC 2013)
PASS   : tst_qpromise::initTestCase()
PASS   : tst_qpromise::resolveSync()
PASS   : tst_qpromise::resolveSync_void()
PASS   : tst_qpromise::resolveDelayed()
PASS   : tst_qpromise::rejectSync()
PASS   : tst_qpromise::rejectDelayed()
PASS   : tst_qpromise::rejectThrows()
PASS   : tst_qpromise::thenReturns()
PASS   : tst_qpromise::thenThrows()
PASS   : tst_qpromise::thenNullPtr()
PASS   : tst_qpromise::thenSkipResult()
PASS   : tst_qpromise::thenDelayedResolved()
PASS   : tst_qpromise::thenDelayedRejected()
PASS   : tst_qpromise::failSameType()
PASS   : tst_qpromise::failBaseClass()
PASS   : tst_qpromise::failCatchAll()
PASS   : tst_qpromise::finallyFulfilled()
PASS   : tst_qpromise::finallyFulfilled_void()
PASS   : tst_qpromise::finallyRejected()
PASS   : tst_qpromise::finallyRejected_void()
PASS   : tst_qpromise::finallyThrows()
PASS   : tst_qpromise::finallyThrows_void()
PASS   : tst_qpromise::finallyDelayedResolved()
PASS   : tst_qpromise::finallyDelayedRejected()
PASS   : tst_qpromise::tapFulfilled()
PASS   : tst_qpromise::tapFulfilled_void()
PASS   : tst_qpromise::tapRejected()
PASS   : tst_qpromise::tapRejected_void()
PASS   : tst_qpromise::tapThrows()
PASS   : tst_qpromise::tapThrows_void()
PASS   : tst_qpromise::tapDelayedResolved()
PASS   : tst_qpromise::tapDelayedRejected()
PASS   : tst_qpromise::timeoutFulfilled()
PASS   : tst_qpromise::timeoutRejected()
PASS   : tst_qpromise::timeoutReject()
PASS   : tst_qpromise::delayFulfilled()
PASS   : tst_qpromise::delayRejected()
PASS   : tst_qpromise::cleanupTestCase()
Totals: 38 passed, 0 failed, 0 skipped, 0 blacklisted, 5218ms
********* Finished testing of tst_qpromise *********

I confirm that also with 4.8.4 GCC is working well too. 

Your fix is important because Qt is still distributed with MSVC-2013 hence a lot of people are using it with a non fully compliant compiler with c++11. Well done. 

thanks

**Comment by simonbrunel** [comment]
Thanks @paperab for your tests, I merged the branch in master (https://github.com/simonbrunel/qtpromise/commit/931d5d5b135ad9192028b0b3d2d3df75360adb76)
