### ISSUE TITLE
want to unpack and assign qtpromise value to a C++ private member

### ISSUE THREAD

**Issue by willmafh** [simonbrunel/qtpromise#21]
Hi...
I'm using QtPromise but encountered a problem...I need a way to unpack QPromise<QString> and then assign the value to a private member of a class...But I can't do that because THE this pointer can't be accessed in the **then** of qtpromise facility...Is there anyone can't tell me how to do that...Thank you...

**Comment by pwuertz** [comment]
`this` needs to be captured within the `then` lambda. Be aware of situations where `then` might out-live `this` and handle such cases with some sort of smart pointer.
