### ISSUE TITLE
How can I flatten nested promises?

### ISSUE THREAD

**Issue by unnamed42** [simonbrunel/qtpromise#27]
I have a task that can be splitted into two steps, the first step is:
```
QPromise<Result1> step1(const QString &);
```
And the next step depends on the output of `step1`, something like:
```
QPromise<void> step2(const Result1 &);
```

But the task cannot be implemented like this:
```
QPromise<void> task(const QString &s) {
    // this is incorrect, return type is QPromise<QPromise<void>>
    return step1(s).then(step2);
    // also incorrect, you lose control of step2's promise
    return step1(s).then([](const Result1 &r) {
        step2(r);
    });
}
```
So is there something can flatten nested promises?

**Comment by pwuertz** [comment]
Chained promises are usually flattened by default. This example here works as expected:
```cpp
const auto step1 = [](const QString& x) { return QPromise<int>::resolve(42); };
const auto step2 = [](const int x) { return QPromise<void>::resolve(); };
auto result = step1("test").then(step2);
using ExpectedType = QPromise<void>;
static_assert(std::is_same_v<decltype(result), ExpectedType>, "Unexpected result type");
```
Used `int` instead of your unknown `Result` type. You didn't by any chance typedef `Result` to `QPromise<void>`?

**Comment by simonbrunel** [comment]
> // also incorrect, you lose control of step2's promise

@unnamed42 that's probably because you need to return the result of `step2` from the callback:

```cpp
QPromise<void> task(const QString &s) {
    return step1(s).then([](const Result1 &r) {
        // Must return the promise returned by step2() in order to delay 
        // the promise returned by task() until step2 is fully resolved.
        return step2(r);
    });
}
```

> return step1(s).then(step2);

This should work, can you share a minimal project that reproduces this issue so I can debug?

**Comment by unnamed42** [comment]
Yes it is automatically flattened, problem solved. Thank you!
