### ISSUE TITLE
"Getting Started" section for CMake could be improved

### ISSUE THREAD

**Issue by sthlm58** [simonbrunel/qtpromise#38]
"Getting Started" section, for the *CMake (Fetch Content)* part ([here](https://qtpromise.netlify.app/qtpromise/getting-started.html#cmake-fetchcontent)) indicates that the `tag` to be used is `origin/0.6.0`.

This version, however, was not yet released.

So, my next step was to use the one last released (`origin/0.5.0`). This didn't work because the `origin` prefix was unnecessary. Standalone `0.5.0` turned out not to have proper CMake support. Only after switching to `master` it finally worked.

I'd suggest to improve the documentation to reflect the usage.

Otherwise, great work! Thanks!

**Comment by simonbrunel** [comment]
Thanks @sthlm58! I thought I released v0.6.0 earlier this year, but no.

I fixed the docs and tagged [v0.6.0](/simonbrunel/qtpromise/releases/tag/v0.6.0) so it should now work as expected.
