### ISSUE TITLE
Release Candidate for v0.7.0

### ISSUE THREAD

**Issue by evan-swinney** [simonbrunel/qtpromise#55]
Hello, I noticed in the documentation there's references to a v0.7.0, but no such tag exists currently. Could we get a semi-stable release of v0.7.0 that has the Qt6 support within it, or are there more features to be planned for the official v0.7.0 release?

Thanks!

**Comment by simonbrunel** [comment]
Thanks @evan-swinney! I'm not sure anymore why I didn't release it earlier.

[v0.7.0](https://github.com/simonbrunel/qtpromise/releases/tag/v0.7.0) is now tagged!
