### ISSUE TITLE
Different .then behavior than expected

### ISSUE THREAD

**Issue by evan-swinney** [simonbrunel/qtpromise#56]
Perhaps this is my misunderstanding of how the library works, but it seems there's a subtle difference of how .then() statements can be chained together:

Take the following example:
```
QtPromise::QPromise<QString> runShellCommand(const QString& command, const QStringList& arguments = {})
{
    QProcess *process = new QProcess();
    return QtPromise::QPromise<ProcessResult>([=](const auto& resolve, const auto& reject){
        QObject::connect(process, &QProcess::finished, process, &QProcess::deleteLater);
        QObject::connect(process, &QProcess::finished, [=](int exitCode, QProcess::ExitStatus exitStatus){
            if( exitStatus != QProcess::NormalExit ) {
                reject(exitStatus);
            }
            resolve(process->readAllStandardOutput());
        });
        qDebug() << "Running:" << command << arguments;
        process->start(command, arguments);
    });
}

QtPromise::QPromise<void> runScriptVersion1()
{
    QtPromise::QPromise<void> p = QtPromise::attempt([this](){
        return runShellCommand("ls")
        .then([](const QString& output){
            qDebug() << output;
        });
    });
    
    p.then([](){
        return runShellCommand("ls")
        .then([](const QString& output){
            qDebug() << output;
        });
    });
    
    p.then([](){
        return runShellCommand("pwd")
        .then([](const QString& output){
            qDebug() << output;
        });
    });
    
    p.then([](){
        return runShellCommand("ls")
        .then([](const QString& output){
            qDebug() << output;
        });
    });
    
    return p;
}

QtPromise::QPromise<void> runScriptVersion2()
{
    return QtPromise::QPromise<void> p = QtPromise::attempt([this](){
        return runShellCommand("ls")
        .then([](const QString& output){
            qDebug() << "ls" << output;
        });
    })
    .then([](){
        return runShellCommand("ls")
        .then([](const QString& output){
            qDebug() << "pwd" << output;
        });
    })
    .then([](){
        return runShellCommand("pwd")
        .then([](const QString& output){
            qDebug() << "ls" << output;
        });
    })
    .then([](){
        return runShellCommand("ls")
        .then([](const QString& output){
            qDebug() << output;
        });
    });
}
```

Notice the different of how I chained together the .then() statements with and without ending the statement with `;`

Version 1 I get the behavior of:
```
Running command: ls
Running command: pwd
Running command: ls
ls: <output>
pwd: <output>
ls: <output>
```

Version 2 I get the behavior of:
```
Running command: ls
ls: <output>
Running command: pwd
pwd: <output>
Running command: ls
ls: <output>
```

I would expect behavior 2 on both versions, but in the first version 3 processes get spawned, then all of the output. I'd like the second version as it's more script-like behavior.

The reason this matters to me is version 1 is actually contained within a loop, and I've effectively loop unrolled it. I figured I could "build" the .then() statements each loop iteration. Here's an example:
```
QtPromise::QPromise<void> runScript(const QStringList& commands)
{
    QtPromise::QPromise<void> p = QtPromise::attempt([](){}); // Need this because there's no default constructor? Probably a better way to do this
    for(const QString& command: commands) { // Assume commands = QStringList{"ls", "pwd", "ls"}
        p.then([](){
            return runShellCommand(command)
            .then([](const QString& output){
                qDebug() << output;
            });
        });
    }
    return p;
}
```

Let me know if there's just an overall better way to do this. Perhaps all I need is a .wait() at the end of the .then() statement in the loop? Also I wouldn't mind some guidance on how to do the promise structure better in the function without having to do the .attempt()

Thanks so much! This library has been so helpful already in other contexts for *years* now. :)

**Comment by simonbrunel** [comment]
> This library has been so helpful already in other contexts for years now. :)

That's really good to read! Thanks 😃

It's indeed the expected behavior: `.then()` is non-blocking and will return immediately a new (pending) promise. For example, the command `c2` in `p1.then([]() { return c2; })` will be executed when `p1` is resolved. Then `p2` will resolve when the command `c2` is finished. 

Your version 1 will run all commands in parallel (but in this case, there are better ways to do it). See your version 1 as:

```cpp
auto p2 = p.then([]() { return c2; });
auto p3 = p.then([]() { return c3; });
auto p4 = p.then([]() { return c4; });

return p; // p is already resolved at this point, but c2, c3 and c4 are still not executed.
```

So, if you want to execute all your commands in series, then you need to chain each return promise (i.e. your version 2).  I'm a bit rusty with this lib, but I'm thinking of 2 solutions:

```cpp
// Run all commands in series
auto p = QtPromise.resolve();
for(const QString& command: commands) {
  p = p.then([]() { 
         return runShellCommand(command); 
       })
       .tap([](const QString& output){ 
         qDebug() << output; 
       });
}
return p;
```

Or *maybe* using the [.reduce() helper](https://qtpromise.netlify.app/qtpromise/helpers/reduce.html):

```cpp
return QtPromise::reduce(commands, [](const QString& previousCommandOutput, const QString& command) {
  return runShellCommand(command).tap([](const QString& output){ 
    qDebug() << output; 
  });
}, QString{});
```

Ideally, we would need a new `.eachSeries()` helper or a new `concurrency` arg to the existing `.each()` helper.

**Comment by evan-swinney** [comment]
I've just realized I left this open and never responded, but your first suggestion is exactly what I wanted and needed. 😄 

Many thousands of lines of code have now been written using that paradigm. Works great for needing async, yet "scriptable" actions.

I'll close this issue now! Thanks!
