### ISSUE TITLE
Add map/filter/reduce methods for sequences of promises

### ISSUE THREAD

**Issue by geiseri** [simonbrunel/qtpromise#7]
This library is a lifesaver.  With JavaScript I use `bluebirdjs` for promises and it has some very handy helpers for containers.  When dealing with `Promise::all(...)` post processing the returned sequence is a bit combersome.  Example for filter:

```cpp
QVector<QPromise<QByteArray> > promises{
    download(QUrl("http://a...")),
    download(QUrl("http://b...")),
    download(QUrl("http://c..."))
};

QPromise<QByteArray>::all(promises)
    .then([](const QVector<QByteArray>& res) {
       QVector<QByteArray> out;
       std::copy_if (res.begin(), res.end(), std::back_inserter(out), [](QByteArray a){
           // return true/false based on some rule
       });
       return out;
    })
    .then([](const QVector<QByteArray>& res) {
       // do something with it
    });
``` 
What I would like to have is something like this:

```cpp
QVector<QPromise<QByteArray>> promises{
    download(QUrl("http://a...")),
    download(QUrl("http://b...")),
    download(QUrl("http://c..."))
};

QPromise<QByteArray>::all(promises)
    .filter([](QByteArray a){
           // return true/false based on some rule
       }))
    .then([](const QVector<QByteArray>& res) {
       // do something with it
    });
```

What would really be cool is to be able to do something like this:

```cpp
QVector<QPromise<QByteArray>> promises{
    download(QUrl("http://a...")),
    download(QUrl("http://b...")),
    download(QUrl("http://c..."))
};

QPromise<QByteArray>::all(promises)
    .map([](QByteArray a) {
        return QJsonDocument::fromJson(a).object();
    })
    .filter([](QJsonObject o){
           return o['result'].toInt() == 200;
     })
    .then([](const QVector<QJsonObject >& res) {
       // do something with it
    });
```

**Comment by simonbrunel** [comment]
Thanks @geiseri

It sounds like a good addition and I may already have some code for `map` and `filter` that follows the bluebird API (still need to write tests and docs and make sure the public API is robust enough). These methods also need to handle promise results:

```cpp
QPromise<QByteArray>::all(promises)
  .map([](const QByteArray& a) {
    return QPromise<QJsonObject>([](...) {
      // async ...
    });
  })
  .filter([](const QJsonObject& o) {
     return QPromise<bool>([](...) {
       // async ...
     });
  })
  // ...
```

**Comment by simonbrunel** [comment]
All these methods are now implemented:

- each: since [v0.4.0](/simonbrunel/qtpromise/milestone/3) (051fed5fbc881323bdf87712538c6fc7cf6a4160)
- filter: since [v0.4.0](/simonbrunel/qtpromise/milestone/3) (4fa7a37750e2005af3e8a6d3eee37cfea3647ad0)
- map: since [v0.4.0](/simonbrunel/qtpromise/milestone/3) (69c07855f476a930345d0a5840ea3dfadc296c07)
- reduce: since [v0.5.0](/simonbrunel/qtpromise/milestone/4) (d3bd28bab47fc7c63702b4f61bd51ca9a50c577f)
