### ISSUE TITLE
Clarify "order guarantee" for QPromise::all(...)

### ISSUE THREAD

**Issue by geiseri** [simonbrunel/qtpromise#8]
This is more of a question/clarification for the documentation, but is there an order of the results in a `QPromise::all(...)`?  Is it ordered as promises are resolved, or is it ordered as they are in the original sequence passed into `QPromise::all(...)`?

**Comment by simonbrunel** [comment]
> The output value is a vector containing all the values of `promises`, **in the same order**.

This is from the [documentation](https://qtpromise.netlify.com/qtpromise/qpromise/all.html) but now you ask the question, I agree that "in the same order" could be confusing. Values are at the respective positions to the original sequence, same as the JavaScript native [Promise::all()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all) and [bluebird](http://bluebirdjs.com/docs/api/promise.all.html). 

Maybe the documentation could be changed for:

> The output value is a vector containing all the values of `promises`, at the respective positions to the original sequence, regardless of completion order.

**Comment by geiseri** [comment]
Sorry,  I am embarrassed that I didn't read the documentation closer. I do think the clarity is good though.  Thanks!

**Comment by simonbrunel** [comment]
No worries! I updated the documentation (d128a5fa8df9), I hope it's a bit clearer ([documentation](https://master--qtpromise.netlify.com/qtpromise/qpromise/all.html)):

> The output value is a vector containing all the values of `promises`, in the same order, i.e., at the respective positions to the original sequence, regardless of completion order.
